name: acceptance

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  acceptance:
    runs-on: ubuntu-latest
    steps:
      - name: 🤘 checkout
        uses: actions/checkout@v3

      - name: ⚙️ Setup Node.js environment
        uses: actions/setup-node@v3.0.0
        with:
          node-version: 18.x
          cache: 'npm'

      - run: npm ci --ignore-scripts

      - name: 🛠️ Build
        run: npm run build

      - name: 🧪 Run acceptance tests
        env:
          TESTS_MOONBEAM_PRIVATE_KEY: ${{ secrets.TESTS_MOONBEAM_PRIVATE_KEY }}
          TESTS_POLKADOT_SURI: ${{ secrets.TESTS_POLKADOT_SURI }}
        run: npm run test:acc
