name: build

on: push

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - name: 🤘 checkout
        uses: actions/checkout@v3

      - name: ⚙️ Setup Node.js environment
        uses: actions/setup-node@v3.0.0
        with:
          node-version: 16.x
          cache: 'npm'

      - run: npm ci --ignore-scripts
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: 🛠️ Build
        run: npm run build
