name: lint

on: push

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: 🤘 checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - name: ⚙ Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'pnpm'

      - run: pnpm install --ignore-scripts

      - name: 🛠️ Build
        run: pnpm run build

      - name: 🧪 Run TypeCheck
        run: pnpm run typecheck

      - name: 🧪 Run ESLint
        run: pnpm run lint
