name: publish dev versions

on:
  workflow_dispatch:

jobs:
  publish-dev-versions:
    runs-on: ubuntu-latest
    steps:
      - name: 🤘 checkout
        uses: actions/checkout@v4

      - name: ⚙️ Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'

      - name: 🔐 Authenticate with NPM
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

      - name: Update npm
        run: npm i -g npm@latest
      
      - name: node/npm version
        run: node --version && npm --version    

      - run: npm ci --ignore-scripts

      - name: ✌️ Update versions
        run: npx bun ./scripts/update-dev-versions.ts

      - name: ✌️ Print versions
        run: find ./packages -name 'package.json' -not -path '*/node_modules/*' -exec grep -H 'version' {} +

      - name: 🛠️ Build
        run: npm run build

      - name: 🚀 Publish types
        working-directory: ./packages/types
        run: npm publish --tag dev

      - name: 🚀 Publish utils
        working-directory: ./packages/utils
        run: npm publish --tag dev

      - name: 🚀 Publish builder
        working-directory: ./packages/builder
        run: npm publish --tag dev

      - name: 🚀 Publish config
        working-directory: ./packages/config
        run: npm publish --tag dev

      - name: 🚀 Publish sdk
        working-directory: ./packages/sdk
        run: npm publish --tag dev
