name: publish dev or beta

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'NPM tag'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - beta
      package:
        description: 'packages'
        required: true
        default: 'all'
        type: choice
        options:
          - all
          - config
          - sdk
          - utils
          - transact

jobs:
  publish-beta-dev:
    runs-on: ubuntu-latest
    steps:
      - name: 🤘 checkout
        uses: actions/checkout@v3

      - name: ⚙️ Setup Node.js environment
        uses: actions/setup-node@v3.0.0
        with:
          node-version: 16.x
          cache: 'npm'

      - name: 🔐 Authenticate with NPM
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

      - run: npm ci --ignore-scripts

      - name: 🛠️ Build
        run: npm run build

      - name: 🚀 Publish utils
        if: ${{ inputs.tag == 'all' }} || ${{ inputs.tag == 'utils' }}
        working-directory: ./packages/utils
        run: |
          npm version $(../../scripts/get_next_version.sh xcm-utils ${{ inputs.tag }}) --no-git-tag-version
          npm publish --tag ${{ inputs.tag }}

      - name: 🚀 Publish config
        if: ${{ inputs.tag == 'all' }} || ${{ inputs.tag == 'config' }}
        working-directory: ./packages/config
        run: |
          npm version $(../../scripts/get_next_version.sh xcm-config ${{ inputs.tag }}) --no-git-tag-version
          npm publish --tag ${{ inputs.tag }}

      - name: 🚀 Publish sdk
        if: ${{ inputs.tag == 'all' }} || ${{ inputs.tag == 'sdk' }}
        working-directory: ./packages/sdk
        run: |
          npm version $(../../scripts/get_next_version.sh xcm-sdk ${{ inputs.tag }}) --no-git-tag-version
          npm publish --tag ${{ inputs.tag }}

      - name: 🚀 Publish transact
        if: ${{ inputs.tag == 'all' }} || ${{ inputs.tag == 'transact' }}
        working-directory: ./packages/transact
        run: |
          npm version $(../../scripts/get_next_version.sh xcm-transact ${{ inputs.tag }}) --no-git-tag-version
          npm publish --tag ${{ inputs.tag }}
