name: publish dev or beta

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'NPM tag'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - beta
jobs:
  publish-beta-dev:
    runs-on: ubuntu-latest
    steps:
      - name: 🤘 checkout
        uses: actions/checkout@v3

      - name: ⚙️ Setup Node.js environment
        uses: actions/setup-node@v3.0.0
        with:
          node-version: 16.x
          cache: 'npm'

      - run: npm ci --ignore-scripts
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: 🛠️ Build
        run: npm run build

      - name: Get last version number
        run: echo "last_version_number=$(npm show @moonbeam-network/xcm-sdk dist-tags.${{ inputs.tag }} | grep -Eo '[0-9]+$')" >> $GITHUB_ENV
      - name: Increase version number
        run: echo "new_version_number=$((${{ env.last_version_number }}+1))" >> $GITHUB_ENV
      - name: Get new version
        run: echo "new_version=0.0.1-${{ inputs.tag }}.${{ env.new_version_number }}" >> $GITHUB_ENV

      - name: 🚀 Publish config
        working-directory: ./packages/config
        run: |
          npm version ${{ env.new_version }} --no-git-tag-version
          npm publish --tag ${{ inputs.tag }}

      - name: 🚀 Publish sdk
        working-directory: ./packages/sdk
        run: |
          npm version ${{ env.new_version }} --no-git-tag-version
          npm publish --tag ${{ inputs.tag }}
