name: unit

on: push

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - name: 🤘 checkout
        uses: actions/checkout@v3

      - name: ⚙️ Setup Node.js environment
        uses: actions/setup-node@v3.0.0
        with:
          node-version: 18.x
          cache: 'npm'

      - run: npm ci --ignore-scripts

      - name: 🧪 Run unit tests
        run: npm run test:ci
