name: XCM WS endpoints monitor

on:
  workflow_dispatch:
  schedule:
    # Runs every 30 minutes
    - cron: '*/30 * * * *'

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      - name: 🤘 checkout
        uses: actions/checkout@v4

      - name: ⚙️ Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'
      - uses: oven-sh/setup-bun@v1         

      - name: Update npm
        run: npm i -g npm@9

      - name: ⬇️ install
        run: npm ci --ignore-scripts

      - name: 🛠️ Build
        run: npm run build

      - name: 💻 Run script
        run:  bun ./scripts/check-websockets.ts --slack-wh=${{ secrets.SLACK_WEBHOOK_URL }}
